const products = [
  {
    id: 1,
    titleKey: "theScream",
    price: "$799",
    image: "/images/the-scream.jpg",
    artistKey: "edvardMunch",
    related: [2, 17, 18],
  },
  {
    id: 2,
    titleKey: "starryNight",
    price: "$1199",
    image: "/images/starry-night.jpg",
    artistKey: "vincentVanGogh",
    related: [1, 13, 18],
  },
  {
    id: 3,
    titleKey: "monaLisa",
    price: "$1199",
    image: "/images/mona-lisa.webp",
    artistKey: "leonardoDaVinci",
    related: [6, 10, 14],
  },
  {
    id: 4,
    titleKey: "theHayWain",
    price: "$899",
    image: "/images/the-hay-wain.jpg",
    artistKey: "johnConstable",
    related: [9, 13, 2],
  },
  {
    id: 5,
    titleKey: "persistenceOfMemory",
    price: "$1299",
    image: "/images/persistence-of-memory.jpg",
    artistKey: "salvadorDali",
    related: [17, 1, 18],
  },
  {
    id: 6,
    titleKey: "girlWithPearlEarring",
    price: "$1099",
    image: "/images/girl-with-pearl-earing.webp",
    artistKey: "johannesVermeer",
    related: [3, 12, 16],
  },
  {
    id: 7,
    titleKey: "greatWaveOffKanagawa",
    price: "$999",
    image: "/images/great-wave.jpg",
    artistKey: "hokusai",
    related: [9, 13, 4],
  },
  {
    id: 8,
    titleKey: "theKiss",
    price: "$1399",
    image: "/images/the-kiss.jpg",
    artistKey: "gustavKlimt",
    related: [10, 6, 3],
  },
  {
    id: 9,
    titleKey: "waterLilies",
    price: "$899",
    image: "/images/water-lilies.jpg",
    artistKey: "claudeMonet",
    related: [13, 7, 4],
  },
  {
    id: 10,
    titleKey: "birthOfVenus",
    price: "$1499",
    image: "/images/birth-of-venus.jpg",
    artistKey: "sandroBotticelli",
    related: [3, 8, 14],
  },
  {
    id: 11,
    titleKey: "americanGothic",
    price: "$799",
    image: "/images/american-gothic.jpg",
    artistKey: "grantWood",
    related: [12, 3, 6],
  },
  {
    id: 12,
    titleKey: "nightWatch",
    price: "$1299",
    image: "/images/night-watch.jpg",
    artistKey: "rembrandt",
    related: [6, 11, 16],
  },
  {
    id: 13,
    titleKey: "impressionSunrise",
    price: "$999",
    image: "/images/impression_sunrise.jpg",
    artistKey: "claudeMonet",
    related: [2, 9, 18],
  },
  {
    id: 14,
    titleKey: "creationOfAdam",
    price: "$1399",
    image: "/images/creation-of-adam.jpg",
    artistKey: "michelangelo",
    related: [10, 3, 16],
  },
  {
    id: 15,
    titleKey: "libertyLeadingThePeople",
    price: "$1199",
    image: "/images/liberty-leading-the-people.jpg",
    artistKey: "eugeneDelacroix",
    related: [12, 11, 14],
  },
  {
    id: 16,
    titleKey: "lastSupper",
    price: "$1599",
    image: "/images/last-supper.jpg",
    artistKey: "leonardoDaVinci",
    related: [14, 3, 12],
  },
  {
    id: 17,
    titleKey: "sonOfMan",
    price: "$1099",
    image: "/images/son-of-man.JPG",
    artistKey: "reneMagritte",
    related: [5, 1, 2],
  },
  {
    id: 18,
    titleKey: "cafeTerraceAtNight",
    price: "$999",
    image: "/images/cafe-terrace-at-night.jpg",
    artistKey: "vincentVanGogh",
    related: [2, 13, 9],
  },
];

export default products;

